/*
 * This source file was generated by the Gradle 'init' task
 */
package com.nimdec.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RESTApi {

    public static void main(String[] args) {
        var appContext = SpringApplication.run(RESTApi.class, args);
        System.out.println();
    }

}
